// <auto-generated /> — VSCommandTable.vsct 의 GuidSymbol/IDSymbol 과 1:1 대응
using System;

namespace LocalMcpVsExtension
{
    internal static class PackageGuids
    {
        public const string guidLocalMcpVsExtensionPackageString =
            "d8f7a321-5b2e-4c9f-b6e8-1a2b3c4d5e6f";

        public static readonly Guid guidLocalMcpVsExtensionPackage =
            new Guid(guidLocalMcpVsExtensionPackageString);

        public const string guidLocalMcpVsExtensionPackageCmdSetString =
            "e9a8b712-6c3f-4d0a-c7f9-2b3c4d5e6f7a";

        public static readonly Guid guidLocalMcpVsExtensionPackageCmdSet =
            new Guid(guidLocalMcpVsExtensionPackageCmdSetString);
    }

    internal static class PackageIds
    {
        public const int ShowSummaryWindowCommand = 0x0100;
    }
}
